kind: Pod
apiVersion: v1
metadata:
 name: environment 
 labels:
  course: devops
  trainer: naveen
spec:
 containers:
  - name: nginx
    image: nginx
    env:
      - name: course
        value: 'kubernetes'
      - name: duration
        value: '200'      