kind: Pod
apiVersion: v1
metadata:
 name: pod-1
 labels:
  name: pod-1
  purpose: affinity
spec:
 containers:
 - name: nginx
   image: nginx
---
kind: Pod
apiVersion: v1
metadata:
 name: pod-2
 labels:
  name: pod-1
  purpose: affinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: security
            operator: In
            values:
            - S1
        topologyKey: topology.kubernetes.io/zone
 containers:
 - name: nginx
   image: nginx