apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  storageClassName: "ebx-dynamic" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-claim # pv metadata name
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-dynamic
  labels:
   purpose: ebs-dynamic
   project: expense
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  # nodeSelector:  # whenver u want to assign a pod to particular reging you can use nodeSelector
  #  topology.kubernetes.io/zone: us-east-1b     
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim # pvc medatadata name